terraform {
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "~> 1.60"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }

  required_version = ">= 1.5.0"
}

provider "hcloud" {
  token = var.hcloud_token
}

# ──────────────────────────────────────────────
# SSH key (generated by Terraform)
# ──────────────────────────────────────────────

resource "tls_private_key" "ssh" {
  algorithm = "ED25519"
}

resource "local_sensitive_file" "ssh_private_key" {
  content         = tls_private_key.ssh.private_key_openssh
  filename        = "${path.module}/id_ed25519"
  file_permission = "0600"
}

resource "local_file" "ssh_public_key" {
  content         = tls_private_key.ssh.public_key_openssh
  filename        = "${path.module}/id_ed25519.pub"
  file_permission = "0644"
}

locals {
  user_data = templatefile("${path.module}/user-data.yml", {
    SSH_PUBLIC_KEY   = tls_private_key.ssh.public_key_openssh
    OPENCLAW_VERSION = var.openclaw_version
  })
}

resource "hcloud_ssh_key" "me" {
  name       = "openclaw-key"
  public_key = tls_private_key.ssh.public_key_openssh
}

# ──────────────────────────────────────────────
# Firewall — SSH only (gateway uses SSH tunnel)
# ──────────────────────────────────────────────

resource "hcloud_firewall" "openclaw_fw" {
  # checkov:skip=CKV2_HCLOUD_4:delete_protection is not supported on hcloud_firewall resources
  # checkov:skip=CKV2_HCLOUD_5:SSH must be reachable from any IP (no static IP/VPN available)
  name = "openclaw-fw"

  rule {
    direction  = "in"
    protocol   = "tcp"
    port       = "22"
    source_ips = ["0.0.0.0/0", "::/0"]
  }

  apply_to {
    label_selector = "role=openclaw"
  }
}

# ──────────────────────────────────────────────
# Server
# ──────────────────────────────────────────────

resource "hcloud_server" "openclaw" {
  name        = var.server_name
  server_type = var.server_type
  image       = "ubuntu-24.04"
  location    = var.location

  ssh_keys = [hcloud_ssh_key.me.id]

  backups            = true
  delete_protection  = var.enable_protection
  rebuild_protection = var.enable_protection

  labels = {
    role = "openclaw"
  }

  user_data = local.user_data

  lifecycle {
    ignore_changes = [user_data]
  }
}

# ──────────────────────────────────────────────
# Outputs
# ──────────────────────────────────────────────

output "server_ip" {
  value       = hcloud_server.openclaw.ipv4_address
  description = "Public IPv4 address of the OpenClaw server."
}

output "ssh_command" {
  value       = "ssh -i ${local_sensitive_file.ssh_private_key.filename} molt@${hcloud_server.openclaw.ipv4_address}"
  description = "SSH command to connect to the server."
}

output "ssh_public_key" {
  value       = tls_private_key.ssh.public_key_openssh
  description = "Generated SSH public key (ed25519)."
}
