#cloud-config

# ──────────────────────────────────────────────
# User
# ──────────────────────────────────────────────
users:
  - name: molt
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${SSH_PUBLIC_KEY}

# ──────────────────────────────────────────────
# System
# ──────────────────────────────────────────────
package_update: true
package_upgrade: true
timezone: Europe/Berlin

# Prevent interactive debconf dialogs (e.g. kernel upgrade notices)
bootcmd:
  - [
      sh,
      -c,
      echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections,
    ]

packages:
  - ca-certificates
  - curl
  - gnupg
  - build-essential
  - fail2ban
  - unattended-upgrades

# ──────────────────────────────────────────────
# Swap (1 GB — safety net for a 4 GB server)
# ──────────────────────────────────────────────
swap:
  filename: /swapfile
  size: 1073741824
  maxsize: 1073741824

# ──────────────────────────────────────────────
# Bootstrap
# ──────────────────────────────────────────────
runcmd:
  # Harden SSH: disable root & password login
  - sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
  - systemctl restart sshd

  # Enable fail2ban
  - systemctl enable --now fail2ban

  # Enable unattended security upgrades
  - DEBIAN_FRONTEND=noninteractive dpkg-reconfigure -f noninteractive unattended-upgrades

  # Install Node.js 22.x via NodeSource (remove system Node 18 first)
  - DEBIAN_FRONTEND=noninteractive apt-get remove -y nodejs libnode109 2>/dev/null || true
  - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  - DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs

  # Install OpenClaw globally
  - npm install -g openclaw@latest

  # Signal completion
  - touch /home/molt/.openclaw-ready
  - chown molt:molt /home/molt/.openclaw-ready
