#cloud-config

# ──────────────────────────────────────────────
# User
# ──────────────────────────────────────────────
users:
  - name: molt
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${SSH_PUBLIC_KEY}

# ──────────────────────────────────────────────
# System
# ──────────────────────────────────────────────
package_update: true
package_upgrade: true
timezone: Europe/Berlin

# Prevent interactive debconf dialogs (e.g. kernel upgrade notices)
bootcmd:
  - [
      sh,
      -c,
      echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections,
    ]

packages:
  - ca-certificates
  - curl
  - gnupg
  - build-essential
  - fail2ban
  - unattended-upgrades

# ──────────────────────────────────────────────
# Swap (1 GB — safety net for a 4 GB server)
# ──────────────────────────────────────────────
swap:
  filename: /swapfile
  size: 1073741824
  maxsize: 1073741824

# ──────────────────────────────────────────────
# Bootstrap
# ──────────────────────────────────────────────
runcmd:
  # Harden SSH: disable root & password login
  - sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
  - systemctl restart sshd

  # Enable fail2ban
  - systemctl enable --now fail2ban

  # Enable unattended security upgrades
  - DEBIAN_FRONTEND=noninteractive dpkg-reconfigure -f noninteractive unattended-upgrades

  # Ensure keyrings directory exists for GPG-verified apt repos
  - install -m 0755 -d /etc/apt/keyrings

  # Add Google Cloud CLI apt repo
  - curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /etc/apt/keyrings/cloud.google.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" > /etc/apt/sources.list.d/google-cloud-sdk.list

  # Add Node.js 22.x apt repo (NodeSource, not curl-to-bash)
  - DEBIAN_FRONTEND=noninteractive apt-get remove -y nodejs libnode109 2>/dev/null || true
  - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_22.x nodistro main" > /etc/apt/sources.list.d/nodesource.list

  # Add HashiCorp apt repo (Terraform)
  - curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /etc/apt/keyrings/hashicorp.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list

  # Single apt-get update for all repos, then install
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -y google-cloud-cli nodejs terraform

  # Install OpenClaw globally
  - npm install -g openclaw@${OPENCLAW_VERSION}

  # ──────────────────────────────────────────────
  # Syncthing (official apt repo — not Ubuntu's stale version)
  # ──────────────────────────────────────────────
  - curl -fsSL https://syncthing.net/release-key.gpg | gpg --dearmor -o /etc/apt/keyrings/syncthing.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/syncthing.gpg] https://apt.syncthing.net/ syncthing stable" > /etc/apt/sources.list.d/syncthing.list
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -y syncthing

  # Enable Syncthing as a user service for molt (survives reboots)
  - loginctl enable-linger molt
  - su - molt -c "systemctl --user enable syncthing.service"
  - su - molt -c "systemctl --user start syncthing.service"

  # Create Obsidian vault structure in workspace
  - mkdir -p /home/molt/.openclaw/workspace/.obsidian/plugins
  - mkdir -p /home/molt/.openclaw/workspace/00-inbox
  - mkdir -p /home/molt/.openclaw/workspace/research
  - mkdir -p /home/molt/.openclaw/workspace/templates

  # .stignore — hide agent internals from Syncthing (Philip doesn't need these)
  - |
    cat > /home/molt/.openclaw/workspace/.stignore << 'STIGNORE'
    // Syncthing ignore patterns — agent internals Philip doesn't need to see
    .git
    .gitignore
    node_modules
    __pycache__
    *.pyc
    .clawhub
    .openclaw
    *.log
    scripts/
    STIGNORE

  # Obsidian community-plugins.json (plugins Philip should install)
  - |
    cat > /home/molt/.openclaw/workspace/.obsidian/community-plugins.json << 'OBSIDIAN'
    [
      "obsidian-kanban",
      "dataview",
      "templater-obsidian",
      "calendar",
      "obsidian-git"
    ]
    OBSIDIAN

  # Obsidian app.json (sane defaults)
  - |
    cat > /home/molt/.openclaw/workspace/.obsidian/app.json << 'OBSIDIAN'
    {
      "newFileLocation": "folder",
      "newFileFolderPath": "00-inbox",
      "attachmentFolderPath": "artifacts",
      "alwaysUpdateLinks": true,
      "showLineNumber": true,
      "strictLineBreaks": false
    }
    OBSIDIAN

  # Daily note template
  - |
    cat > /home/molt/.openclaw/workspace/templates/daily-note.md << 'TEMPLATE'
    # {{date:YYYY-MM-DD}} — {{date:dddd}}

    ## Summary

    ## Key Decisions

    ## Tasks
    - [ ]

    ## Notes

    TEMPLATE

  # Research template
  - |
    cat > /home/molt/.openclaw/workspace/templates/research.md << 'TEMPLATE'
    # Research: {{title}}

    **Date:** {{date:YYYY-MM-DD}}
    **Status:** draft | in-progress | complete

    ## Objective

    ## Sources

    ## Findings

    ## Conclusions

    TEMPLATE

  # Project template
  - |
    cat > /home/molt/.openclaw/workspace/templates/project.md << 'TEMPLATE'
    # Project: {{title}}

    **Created:** {{date:YYYY-MM-DD}}
    **Status:** ideation | spec | design | implementation | qa | deployed

    ## Overview

    ## Requirements

    ## Architecture

    ## Progress

    ## Links

    TEMPLATE

  # Obsidian daily-notes config (folder: memory/, format: YYYY-MM-DD)
  - |
    cat > /home/molt/.openclaw/workspace/.obsidian/daily-notes.json << 'OBSIDIAN'
    {
      "folder": "memory",
      "format": "YYYY-MM-DD",
      "template": "templates/daily-note"
    }
    OBSIDIAN

  # Obsidian core plugins (enable daily-notes + templates)
  - |
    cat > /home/molt/.openclaw/workspace/.obsidian/core-plugins.json << 'OBSIDIAN'
    ["daily-notes","templates","file-explorer","search","graph","tag-pane","command-palette","outline"]
    OBSIDIAN

  # Obsidian templates plugin config (folder: templates/)
  - |
    cat > /home/molt/.openclaw/workspace/.obsidian/templates.json << 'OBSIDIAN'
    {
      "folder": "templates"
    }
    OBSIDIAN

  # ──────────────────────────────────────────────
  # Tailscale (official apt repo)
  # ──────────────────────────────────────────────
  - curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg -o /etc/apt/keyrings/tailscale.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/tailscale.gpg] https://pkgs.tailscale.com/stable/ubuntu noble main" > /etc/apt/sources.list.d/tailscale.list
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -y tailscale
  - systemctl enable tailscaled
  - |
    if [ -n "${TAILSCALE_AUTH_KEY}" ]; then
      tailscale up --authkey="${TAILSCALE_AUTH_KEY}"
      tailscale serve --bg http://127.0.0.1:18789
    fi

  # Fix ownership (cloud-init runs as root)
  - chown -R molt:molt /home/molt/.openclaw

  # Signal completion
  - touch /home/molt/.openclaw-ready
  - chown molt:molt /home/molt/.openclaw-ready
