#cloud-config

# ──────────────────────────────────────────────
# User
# ──────────────────────────────────────────────
users:
  - name: molt
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${SSH_PUBLIC_KEY}

# ──────────────────────────────────────────────
# System
# ──────────────────────────────────────────────
package_update: true
package_upgrade: true
timezone: Europe/Berlin

# Prevent interactive debconf dialogs (e.g. kernel upgrade notices)
bootcmd:
  - [
      sh,
      -c,
      echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections,
    ]

packages:
  - ca-certificates
  - curl
  - gnupg
  - build-essential
  - fail2ban
  - unattended-upgrades

# ──────────────────────────────────────────────
# Swap (1 GB — safety net for a 4 GB server)
# ──────────────────────────────────────────────
swap:
  filename: /swapfile
  size: 1073741824
  maxsize: 1073741824

# ──────────────────────────────────────────────
# Bootstrap
# ──────────────────────────────────────────────
runcmd:
  # Harden SSH: disable root & password login
  - sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
  - systemctl restart sshd

  # Enable fail2ban
  - systemctl enable --now fail2ban

  # Enable unattended security upgrades
  - DEBIAN_FRONTEND=noninteractive dpkg-reconfigure -f noninteractive unattended-upgrades

  # Ensure keyrings directory exists for GPG-verified apt repos
  - install -m 0755 -d /etc/apt/keyrings

  # Add Google Cloud CLI apt repo
  - curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /etc/apt/keyrings/cloud.google.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" > /etc/apt/sources.list.d/google-cloud-sdk.list

  # Add Node.js 22.x apt repo (NodeSource, not curl-to-bash)
  - DEBIAN_FRONTEND=noninteractive apt-get remove -y nodejs libnode109 2>/dev/null || true
  - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_22.x nodistro main" > /etc/apt/sources.list.d/nodesource.list

  # Single apt-get update for both repos, then install
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -y google-cloud-cli nodejs

  # Install OpenClaw globally
  - npm install -g openclaw@${OPENCLAW_VERSION}

  # Signal completion
  - touch /home/molt/.openclaw-ready
  - chown molt:molt /home/molt/.openclaw-ready
